### ISSUE TITLE
Benchmarking example

### ISSUE THREAD

**Issue by ldynia** [abtinmo/django_jsonfield_index#1]
Hi @abtinmo 

Thanks for the medium article about indexing JSONField and benchmarking. I reproduced your example. Unfortunately, the JSONField indexing has no effect what so ever. I got pretty much random times in my test in a range from 0.6s to 0.04s. Here is my repo [https://github.com/ldynia/django-postgres-fields](https://github.com/ldynia/django-postgres-fields) can you confirm that you have the same results ?

Thanks in advance.

**Comment by abtinmo** [comment]
Hey @ldynia ,

Thank you for reading my article :)
In GIN indexing i had same experience after updating a record it  would return response with random query time(takes some time to update the index), but in other cases the result was as i wrote in the article.

**Comment by ldynia** [comment]
Thanks @abtinmo  for reply.

Unfortunately, I am unable to reach those numbers with **BTREE**, **HASH** and **GIN** indexing. 

### Create index on column
```
CREATE INDEX attrs_idx_hash ON demo_product USING HASH((attributes_idx) jsonb_ops);
CREATE INDEX attrs_idx_btree ON demo_product USING BTREE((attributes_idx) jsonb_ops);
CREATE INDEX attrs_idx_gin ON demo_product USING GIN((attributes_idx) jsonb_ops);
CREATE INDEX attrs_idx_gin ON demo_product USING GIN((attributes_idx) jsonb_path_ops);
```

### Create index on column's key
```
CREATE INDEX attrs_idx_hash ON demo_product USING HASH((attributes_idx->name) jsonb_ops);
CREATE INDEX attrs_idx_hash ON demo_product USING HASH((attributes_idx->>name) text_ops);

CREATE INDEX attrs_idx_btree ON demo_product USING BTREE((attributes_idx->name) jsonb_ops);
CREATE INDEX attrs_idx_btree ON demo_product USING BTREE((attributes_idx->>name) text_ops);

CREATE INDEX attrs_idx_gin ON demo_product USING GIN((attributes_idx->name) jsonb_ops);
CREATE INDEX attrs_idx_gin ON demo_product USING GIN((attributes_idx->name) jsonb_path_ops);
```

No matter what index from above statement I execute. All of them results with ~0.600 ms for simple query such:
```
SELECT * FROM demo_product WHERE attributes_idx ->> 'name' = '"32751"'
```

**Comment by ldynia** [comment]
@abtinmo I found the problem. Indexing works as expected. The slow time is caused by wrong json operator in query. The bellow query is executed against GIN indexed jsonb column.

```sql
-- This query results with 600 ms
SELECT * FROM demo_product WHERE "attributes_idx" -> 'name' = '"1546321"';

-- This query results with 1 ms
SELECT * FROM demo_product WHERE "attributes_idx" @> '{"name": "1546321"}';
```

Django's `Model.objects.get()` users `->` [operator](https://www.postgresql.org/docs/9.5/functions-json.html) so now I have to find a way for jsonb to work with it.

**Comment by ldynia** [comment]
I finally managed to reach good performance. I learned how to index column and single elements in column. Furthermore, I discovered that index can be created for various JSON and JSONB operators. Another, thing that influenced the query performance was `LIMIT 21` auto generated by `Model.objects.get()`. All of my experience I share here with this SQL that I used in my example.

```SQL
-- Index normal column with defualt index --
--CREATE INDEX name_idx on demo_product(name_idx);

--Create index on entire doucument. Use `@> '{"key": "val"}'` for performance gain.
--CREATE INDEX "attributes_idx.btree-idx" ON demo_product USING BTREE(attributes_idx);
--CREATE INDEX "attributes_idx.hash-idx" ON demo_product USING HASH(attributes_idx);
--CREATE INDEX "attributes_idx.gin-idx" ON demo_product USING GIN((attributes_idx));

--Create index on doucument's element. Use `"column" -> 'key' = '"val"';` for performance gain.
--CREATE INDEX "attributes_idx.name.btree-idx" ON demo_product USING BTREE((attributes_idx -> 'name'));
--CREATE INDEX "attributes_idx.name.btree-idx2" ON demo_product USING BTREE((attributes_idx ->> 'name'));
--CREATE INDEX "attributes_idx.name.hash-idx" ON demo_product USING HASH((attributes_idx -> 'name'));
--CREATE INDEX "attributes_idx.name.gin-idx" ON demo_product USING GIN((attributes_idx -> 'name'));

-- Delete created indexes --
--DROP INDEX IF EXISTS "attributes_idx.name.btree-idx";
--DROP INDEX IF EXISTS "attributes_idx.name.btree-idx2";
--DROP INDEX IF EXISTS "attributes_idx.name.hash-idx";
--DROP INDEX IF EXISTS "attributes_idx.name.gin-idx";

-- For detail insights add EXPlAIN ANALYZE in front of SELECT --
--SELECT * FROM demo_product order by id desc;
--SELECT * FROM demo_product WHERE "attributes_idx" -> 'name' = '"1546321"';
--SELECT * FROM demo_product WHERE "attributes_idx" ->> 'name' = '1546321';
--SELECT * FROM demo_product WHERE "attributes_idx" @> '{"name": "1546321"}';
--SELECT * FROM demo_product WHERE "attributes_idx" -> 'values' @> '[1356788, 1356789]';
--SELECT * FROM "demo_product" WHERE "attributes_idx" -> 'values' @> '[1535440, 1535441]' LIMIT 1;
```
